---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(nycflights13)

fligths <- read_csv('flights.csv')
airports <- read_csv('airports.csv')
planes <- read_csv('planes.csv')
airlines <- read_csv('airlineas.csv')
weather <- read_csv('weather.csv')


view(flights)

```
1.1 Conecte fligths con planes
```{r}

flights_planes %>% planes
  inner_join(flights, by = c("tailnum" = "tailnum")) %>%
    
flights_planes
```

1.2
```{r}
flights_airlines <- airlines %>%
  inner_join(flights, by = c("carrier")) %>%

flights_airlines
```

1.3
```{r}
flights_airports <- airports %>%
  inner_join(flights, by = c("faa"="origin")) %>%
  inner_join(flights, by = c("faa"="dest"))

flights_airports
```

1.4
```{r}
flights_weather <- flights %>%
  inner_join(weather, by = c("year","month", "day", "hour", "origin")), sufflix = c("_flights", "_weather") %>%

flights_weather


```
2.1
```{r}
flights %>%
  count(year, month, day) %>%
  filter(n>1000) %>%
  arrange(desc(n))

flights
```
2.2

```{r}
flights_selected = flights%>%
dplyr::selected(year:day,hour,origin,dest,tailnum,carrier,arr_delay,dep_delay)


flights_selected


```

2.3
```{r}

airlines
flights_selected

airlines %>%
  left_join(flights_selected,by = c("carrier")) %>%
  select_(-origin, -desc) %>%
  mutate(tot_delay = arr_delay + dep_delay)
```







