---
title: "R Notebook"
output: html_notebook
---

```{r}
poker_vector <- c(140, -50, 20, -120, 240)
roulette_vector <- c(-24, -50, 100, -350, 10)

names(poker_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
poker_vector
names(roulette_vector)  <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
roulette_vector

```


```{r}
age <- 17
result <- age >= 18
result

A_vector <- c(1,2,3)
b_vector <- c(4,5,6)

total_vector <_ A_vector + b_vector

total_vector

total_daily <- poker_vector + roulette_vector
total_daily

total_poker <- sum(poker_vector)
total_poker

total_roulette <- sum(roulette_vector)

sum_total <- sum(total_poker , total_roulette)
sum_total

poker_vector
poker_vector[3]
poker_vector[c(1,2,4)]

roulette_vector[2:5]

poker_vector[c("Monday","Tuesday","Wednesday","Thursday","Friday")]
```


```{r}
matrix(1:9,byrow=TRUE,nrow = 3)
```
```{r}
new_hope <- c (460.998, 314.4)
empire_strike <- c(2980.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strike, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3)
stars_wars_matrix

region <- c("US", "non-US")
titles <- c("A new Hope",  "The empire Strikes Back",  "Return of the Jedi")

colnames(stars_wars_matrix) <- region
rownames(stars_wars_matrix) <- titles

stars_wars_matrix

```

rowSums()
```{r}

worldwide_vector <- rowSums(stars_wars_matrix)
worldwide_vector

all_wars_variable <- cbind(stars_wars_matrix, worldwide_vector)
all_wars_variable

worldwide_cols <- colSums(stars_wars_matrix)
worldwide_cols

all_wars_variable <- rbind(all_wars_variable, worldwide_cols)
all_wars_variable

```

```{r}

non_us_all <- all_wars_variable[1:3,2]
non_us_all

mean (non_us_all)
```
Arithmetic with matrices
```{r}
us_all <- all_wars_variable [1:3,1]
us_all <- us_all * 0.12
us_all


```
```{r}
sex_vector <- c("Male","Female","Female","Male","Male")

factor_sex_vector <- factor(sex_vector)
factor_sex_vector

temperature_vector <- c("High", "Low", "High", "Low", "Medium")
factor_temperatur_vector <- factor(temperature_vector, order=TRUE, levels=c("Low","Medium","High" ))
factor_temperatur_vector

```
Factor levels
```{r}
survey_vector <- c("M", "F", "F", "M","M")
factor_survey_vector <- factor(survey_vector)

factor_survey_vector

levels(factor_survey_vector) <- c("Female","Male")
factor_survey_vector

```
Summarizig a factor
```{r}
summary(survey_vector)
summary(factor_survey_vector)

male <- factor_survey_vector[1]
male

female <- factor_survey_vector[2]
female

male > female

speed_vector <- c("medium", "slow", "slow", "medium","fast")
factor_speed_vector <- factor(speed_vector, ordered = TRUE, levels=c ("slow","medium","fast"))
factor_speed_vector

da2 <- factor_speed_vector[2]
da3 <- factor_speed_vector[1]

da2
da3

da2 > da3

```

Data frames
```{r}
mtcars


```


```{r}
```

