---
title: "R Notebook"
output: html_notebook
---
Intermediate R 

```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"
```

Greater and less than/comparadores 

```{r}
-6 * 5 +2 >= -10 + 1

"raining" <- "table"

TRUE > FALSE

```
Compare vectores and matrices / las estructuras deben ser iguales para poder comparar

```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

linkedin > 15
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin,facebook), nrow = 2, byrow = TRUE)
views

views == 13
views <= 14

```

Operators logical
```{r}

linkedin <= 10 & facebook == 13
views > 11 & views <= 14


```

The if statement
```{r}

medium <- "Linkedin"
num_views <- 14

if (medium == "Linkedin"){
  print("Showing Linkedin information")
} else {
  print("Unknown medium")
}
if(num_views > 15){
  print("You're  popular!")
} else{
  print("Try to be more visible!")
}




```
Customize further: else if

```{r}
if (medium == "Linkedin"){
  print("Showing Linkedin information")
} else if (medium == "Facebook"){
  print("Show Facebook information")
}else{
  print("Unknown medium")
}



```

Else if 2.0
```{r}
number <- 75
result <- ""
if (number < 10){
  if (number < 5) {
    result <- "extra small"
  }
  else{
  result <- "small"
  } 
} else if (number < 100) {
  result <- "medium"
} else {
  result <- "large"
}
 
  print(result) 

```
LOOPS


```{r}
spped <- 64

while(spped > 30){
  print("slow down!")
  spped <- spped - 7
}
if (speed >= 48){
  print("Slow down big time!")
  speed <- speed - 11
}else{
    print("Slow down!")
  speed <- speed - 6
  }
speed    

```

Break
```{r}
speed <- 88

while (speed > 30) {
  print("slow down big time!")
  speed <- speed - 11
}else{
    print("slow down!")
    speed <- speed - 6
  
  }

```
```{r}




```
```{r}

```

For
```{r}
linkedin <- c(16,9,13,5,2,17,14)

for (l in linkedin){
  print(l)
}

for (i in 1:length(linkedin)){
  print(linkedin[i])
  
}
```
Loop over a list
```{r}
nyc <- list(pop=8405837, boroughs=c("Manhattan","Bronx","Brooklyn","Queens","Staten Island"), capital=FALSE)

for (i in 1:length(nyc)){
  if (i==2){
    for (j in 1:length(nyc[[i]])){
      print(nyc[[i]][j])
    }
  }
  
  else{
    print(nyc[[i]])
  }  
}


```
Loop over a matrix
```{r}

views <- matrix(c(linkedin,facebook), nrow = 2, byrow = TRUE)
views
for (row in 1:nrow(views)) {
  for (col in 1:ncol(views)) {
    print(paste("on row",row, "and column", col, "contanins", views[row,col]))
  }
  
}

```

