---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
```


```{r}
tags <- read_csv('tags.csv')
questions <- read_csv('questions.csv')
question_tags <- read_csv('question_tags.csv')
answers <- read_csv('answers.csv')

tags
questions
question_tags
answers
```

left-joining questions and tags 1.1 y 1.2
```{r}
questions %>%
  left_join(question_tags, by = c("id" = "question_id")) %>%
  left_join(tags, by = c("tag_id" = "id")) %>%
  left_join(tags, by = "tag_name") %>%
  
view(questions)
```

1.3 y 1.4
```{r}
questions_with_tags <- tags %>%
  count(tag_name) %>%
  right_join(tags, by=c("tag_name"))%>%
  replace_na(list(n=0))

view(questions_with_tags)

```

Comparing scores across tags
```{r}

questions_with_tags %>%
  group_by(tags_name) %>%
  summarize(mean_score = median(score)) %>%
  arrange(desc(n))


```

finding gaps between question anda answer
```{r}
questions %>%
  inner_join(questions, by=c("id"="question_id"),suffix=c("_questions","_answers"))


```
question and answer utilizando mutate
```{r}
questions %>%
  inner_join(questions, by=c("id"="question_id"),suffix=c("_questions","_answers"))%>%
  mutate(gap = creation_date_answer - creation_date_question)%>%
  

```


```{r}


```

